version: 2
updates:
  - package-ecosystem: "docker"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    groups:
      production-version-updates:
        applies-to: version-updates
        dependency-type: "production"
      development-version-updates:
        applies-to: version-updates
        dependency-type: "development"
      production-security-updates:
        applies-to: security-updates
        dependency-type: "production"
      development-security-updates:
        applies-to: security-updates
        dependency-type: "development"
  - package-ecosystem: "pip"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: "scope"
    directories:
      - "**/*"
    groups: 
      production-version-update:
        applies-to: version-updates
        dependency-type: "production"
      development-version-update:
        applies-to: version-updates
        dependency-type: "development"
      production-security-update:
        applies-to: security-updates
        dependency-type: "production"
      development-security-update:
        applies-to: security-updates
        dependency-type: "development"
