FROM public.ecr.aws/docker/library/python:3.13-bookworm@sha256:3b1b63f17c5197411ee572be110333dae4b9d6f2fbc4f84c790f644e791d356b

LABEL CoronaImageIdentifier=afx-python-clamav IsArtifexImage=true
ENV CoronaImageIdentifier=afx-clamav

ARG PACKAGE_UPDATE_DATE="undefined"
RUN echo "building with PACKAGE_UPDATE_DATE: $PACKAGE_UPDATE_DATE"
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
  clamav \
  clamav-daemon \
  clamav-freshclam \
  clamdscan \
  && rm -rf /var/lib/apt/lists/*

COPY ./clamav/clamd.conf /etc/clamav/clamd.conf

ARG FRESHCLAM_UPDATE_RUN_ID="undefined"
RUN echo "building with FRESHCLAM_UPDATE_RUN_ID: ${FRESHCLAM_UPDATE_RUN_ID}"
RUN ! freshclam | tee /dev/stderr | grep -qF 'cool-down until'
